### ISSUE TITLE
您好，请教一下怎么分别获得Q&A和Q&A+NLG两种数据集呢？

### ISSUE THREAD

**Issue by Jingyilang** [IndexFziQ/MSMARCO-MRC-Analysis#3]

**Comment by IndexFziQ** [comment]
到msmarco.org的dataset column，下载Question Answering V2.1，解压之后就会有两个版本，well-formed.json就对应的是Q&A+NLG。

**Comment by IndexFziQ** [comment]
详细的介绍，请看：https://github.com/microsoft/MSMARCO-Question-Answering

**Comment by Jingyilang** [comment]
> 详细的介绍，请看：https://github.com/microsoft/MSMARCO-Question-Answering



> 到msmarco.org的dataset column，下载Question Answering V2.1，解压之后就会有两个版本，well-formed.json就对应的是Q&A+NLG。

可能是现在又改了？我在这里 http://www.msmarco.org/dataset.aspx 分别下载了 trainset,devset和evalset，解压之后也只分别得到一个解压文件，没有well-formed.json这个版本

**Comment by Jingyilang** [comment]
> 到msmarco.org的dataset column，下载Question Answering V2.1，解压之后就会有两个版本，well-formed.json就对应的是Q&A+NLG。

不过 我看了一下，trainset和devset，都有Answer和wellFormedAnswer两个字段

**Comment by IndexFziQ** [comment]
emm...应该是改了，每个query都有这两个字段吗？well-formed的占比要小一些。如果你要把他们分开，可以把有well-formed answer的query都抽出来。

**Comment by Jingyilang** [comment]
> emm...应该是改了，每个query都有这两个字段吗？well-formed的占比要小一些。如果你要把他们分开，可以把有well-formed answer的query都抽出来。
是的，wellFormedAnswer占比要小一些
